TodoProject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    url(r'^todo/', include('todos.urls')),
)

todos/urls.py
from django.conf.urls import patterns, include, url

from .views import TodoListListView, TodoListDetailView, TodoCreateView, TodoCompleteView

urlpatterns = patterns('',
    url(r'^$', TodoListListView.as_view(), name='todolist_list'),
    url(r'^(?P<pk>\d+)/$', TodoListDetailView.as_view(), name='todolist_detail'),
    url(r'^(?P<pk>\d+)/create/$', TodoCreateView.as_view(), name='todo_create'),
    url(r'^(?P<pk>\d+)/(?P<todo_pk>\d+)/complete/$', TodoCompleteView.as_view(), name='todo_complete'),
)

todos/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User

from .managers import TodoManager

class TodoList(models.Model):
    name = models.CharField(max_length=255)

    def get_absolute_url(self):
        return reverse('todolist_detail', args=(self.pk,))


class Todo(models.Model):
    label = models.CharField(max_length=255)
    is_done = models.BooleanField(default=False)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    list = models.ForeignKey(TodoList)

    def get_complete_url(self):
        return reverse('todo_complete', args=(self.list.pk, self.pk))

    objects = TodoManager()

    class Meta:
        ordering = ('-updated', '-created')

todos/forms.py
from django import forms

class TodoForm(forms.Form):
    label = forms.CharField(max_length=255)

todos/views.py
from django.core.urlresolvers import reverse
from django.shortcuts import redirect
from django.views.generic import ListView, DetailView, CreateView, FormView, View

from .models import Todo, TodoList
from .forms import TodoForm

class TodoListListView(ListView):
    model = TodoList
    template_name = 'todos/todolist_list.html'


class TodoListDetailView(DetailView):
    model = TodoList
    template_name = 'todos/todolist_detail.html'

    def get_context_data(self, *args, **kwargs):
        context = super(TodoListDetailView, self).get_context_data(*args, **kwargs)
        context.update({'todo_form': TodoForm()})
        return context

class TodoCreateView(FormView):
    form_class = TodoForm
    
    def form_valid(self, form):
        todo_list = TodoList.objects.get(pk=self.kwargs['pk'])
        todo = Todo.objects.create(
            label=form.cleaned_data['label'],
            list=todo_list
        )
        return redirect(todo_list.get_absolute_url())

class TodoCompleteView(View):
    def get_todo_list(self):
        return TodoList.objects.get(pk=self.kwargs['pk'])

    def get_todo(self):
        return Todo.objects.get(pk=self.kwargs['todo_pk'])

    def post(self, *args, **kwargs):
        todo_list = self.get_todo_list()
        todo = self.get_todo()

        todo.is_done = True
        todo.save()

        return redirect(todo_list.get_absolute_url())

templates/base.html
<html>
<head>
    <title>TodoListProject</title>
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

templates/todos/todolist_detail.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ todolist.name }}</h1>
<hr>
<h3>Current Todos</h3>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>    
            <th>Created</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        {% for todo in todolist.todo_set.incomplete %}
            <tr>
                <td>{{ todo.label }}</td>
                <td>{{ todo.created|date:'g:i:sA j/n/y' }} <em>({{ todo.created|timesince }} ago)</em></td>
                <td>
                    <form action='{{ todo.get_complete_url }}' method='post'>
                        {% csrf_token %}
                        <button type='submit' class='btn btn-default'>Complete</button>
                    </form>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<hr>
<h3>Past Todos</h3>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>    
            <th>Created</th>
            <th>Completed</th>
        </tr>
    </thead>
    <tbody>
        {% for todo in todolist.todo_set.complete %}
            <tr>
                <td>{{ todo.label }}</td>
                <td>{{ todo.created|date:'g:i:sA j/n/y' }} <em>({{ todo.created|timesince }} ago)</em></td>
                <td>{{ todo.updated|date:'g:i:sA j/n/y' }} <em>({{ todo.updated|timesince }} ago)</em></td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<hr>
<h3>Create New Todo</h3>
<form action="{% url 'todo_create' todolist.pk %}", method='post'>
    {% csrf_token %}
    {{ todo_form.as_p }}
    <input class='btn btn-default' type='submit'>
</form>
</ul>
{% endblock %}

templates/todos/todolist_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Todo Lists</h1>
<ul>
{% for todolist in todolist_list %}
    <li>
        <a href="{{ todolist.get_absolute_url }}">{{ todolist.name }}</a>
    </li>
{% endfor %}
</ul>
{% endblock %}